### ISSUE TITLE
Plugin Gallery outdated and shows invalid HTML

### ISSUE THREAD

**Issue by dipohl** [munin-monitoring/munin#754]
I saw that a recent contribution of plugin doc (see https://github.com/munin-monitoring/contrib/pull/764) is [not shown in Munin Plugin Gallery](http://gallery.munin-monitoring.org/contrib/plugins/network/tc_.html), but I see it in [my instance of the gallery](http://munin-gallery.dipohl-kunden.de/contrib/svn/trunk/plugins/network/tc_.html). So **it seems that the projects gallery is not get updated on a daily base as it was before**.

When I reactivated my instance of the gallery based on the latest state of the scripts here in the repository I found more errors:

1. The "svn co" command used in the build scripts to download the plugin files from the Munin repositories, is not working under current github.

2.  [HTML validation for the category detail pages fails due to "Unclosed element span"](https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fgallery.munin-monitoring.org%2Fcontrib%2Fnetwork-index.html)

I fixed all this issues in my instance of the gallery and pushed the changes to master repo with https://github.com/munin-monitoring/munin/commit/e7a8935b0fe076e9d18a2774d4ec49e906ea7322

Please repair the projects instance of the Munin Plugin Gallery also.

**Comment by sumpfralle** [comment]
I would be willing to help with the maintenance of the service or the server.

**Comment by dipohl** [comment]
- [CSS also invalid](http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fgallery.munin-monitoring.org%2Fmail-index.html&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en)
- Download links don't work for the Core Collection as branch devel vanished in between -> 404: Not Found

**Comment by steveschnepp** [comment]
I just got through my emails & found out yours... 

Got it fixed by now. Sorry for the delay. 

I guess we'll need to fix our process...

**Comment by dipohl** [comment]
[The gallery presents still invalid HTML](https://validator.w3.org/nu/?showsource=yes&doc=http%3A%2F%2Fgallery.munin-monitoring.org%2Fcontrib%2Fnetwork-index.html)

Please apply **all** my commited changes https://github.com/munin-monitoring/munin/commit/e7a8935b0fe076e9d18a2774d4ec49e906ea7322

I didn't fix [the invalid CSS](http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fgallery.munin-monitoring.org%2Fmail-index.html&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en) with my commit as I am not an expert on CSS.
Here the [original author of the JS enhancement](https://github.com/chteuchteu) should rework his template..

**Comment by steveschnepp** [comment]
Hmmm.... It seemed to me that I applied everything...

**Comment by dipohl** [comment]
sorry! I checked and saw, that the missing change was not in my commit unfortunately.
I just pushed it: https://github.com/munin-monitoring/munin/commit/5355e6ba144547d06cdd3b4fbb4281d237a77da4

**Comment by steveschnepp** [comment]
Should be ok now, as I updated & restarted the process

**Comment by dipohl** [comment]
Good! Now this issue is left. Will you contact chteuchteu?
[invalid CSS](http://jigsaw.w3.org/css-validator/validator?uri=http%3A%2F%2Fgallery.munin-monitoring.org%2Fmail-index.html&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en) 
Here the [original author of the JS enhancement](https://github.com/chteuchteu) should rework his template..

**Comment by chteuchteu** [comment]
@dipohl Here he is!
I'll see what I can do.

**Comment by chteuchteu** [comment]
I just opened #770 to fix this. There are remaining errors, but they can be ignored.
